source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CLUUserAgent_Example', :exclusive => true do
  pod "CLUUserAgent", :path => "../"
end

target 'CLUUserAgent_Tests', :exclusive => true do
  pod "CLUUserAgent", :path => "../"

  
end
